site_name: Parloa Interview Documentation
site_description: An asyncio-based scheduling framework designed for execution of periodic task with integrated support for dependency injection, enabling efficient and flexiable task management
repo_url: https://github.com/ManiMozaffar/mock-interview-assignment
site_url: https://ManiMozaffar.github.io/parloa
site_author: Mani Mozaffar
repo_name: ManiMozaffar/mock-interview-assignment
copyright: Maintained by <a href="https://ManiMozaffar.com">Mani Mozaffar</a>.

theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"
  features:
    - content.code.annotate
    - content.tabs.link
    - content.code.copy
    - announce.dismiss
    - navigation.tabs
    - search.suggest
    - search.highlight
  # logo: assets/logo-white.svg
  # favicon: assets/favicon.png

edit_uri: ""

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

extra_css:
  - "extra/tweaks.css"

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

watch:
  - src
plugins:
  - search:
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          options:
            members_order: source
            separate_signature: true
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true

  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: "docs.plugins:on_pre_build"
        on_files: "docs.plugins:on_files"
        on_page_markdown: "docs.plugins:on_page_markdown"

nav:
  - Documentation:
      - Introduction to challenge: introduction.md
      - Design Considerations: design.md
      - Knowledge Base: api/kb.md
